### ISSUE TITLE
Explicit nulls crash naivetokenizerparser

### ISSUE THREAD

**Issue by XCVG** [XCVG/hypergiant-eventscript#2]
engine.tokenizeLine("true + false + null")

_Exception in thread "main" com.xcvgsystems.hypergiant.eventscript.ESDataTypeException
    at com.xcvgsystems.hypergiant.eventscript.ESDataType.getTypeForObject(ESDataType.java:182)
    at com.xcvgsystems.hypergiant.eventscript.ESValue.getType(ESValue.java:41)
    at com.xcvgsystems.hypergiant.eventscript.ESValue.<init>(ESValue.java:25)
    at com.xcvgsystems.hypergiant.eventscript.ESEngine.tokenizeLine(ESEngine.java:261)
    at ESDriver.main(ESDriver.java:21)_

**Comment by XCVG** [comment]
Probably fixed.
